service: serverless-test
frameworkVersion: "2"
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: development
  lambdaHashingVersion: '20201221'
  region: ap-southeast-2
  timeout: 900
  environment:
    ALLOWS_INSECURE_SSL_CERTIFICATES: true


plugins:
  - serverless-plugin-typescript
  - serverless-offline


functions:
  weatherApi:
    handler: src/handlers/weather.handler
    